"""This file was auto-generated by sqlsynthgen but can be edited manually."""
from mimesis import Generic
from mimesis.locales import Locale
from sqlsynthgen.base import FileUploader, TableGenerator
from sqlsynthgen.unique_generator import UniqueGenerator

generic = Generic(locale=Locale.EN_GB)

from sqlsynthgen.providers import BytesProvider

generic.add_provider(BytesProvider)
from sqlsynthgen.providers import ColumnValueProvider

generic.add_provider(ColumnValueProvider)
from sqlsynthgen.providers import NullProvider

generic.add_provider(NullProvider)
from sqlsynthgen.providers import SQLGroupByProvider

generic.add_provider(SQLGroupByProvider)
from sqlsynthgen.providers import TimedeltaProvider

generic.add_provider(TimedeltaProvider)
from sqlsynthgen.providers import TimespanProvider

generic.add_provider(TimespanProvider)
from sqlsynthgen.providers import WeightedBooleanProvider

generic.add_provider(WeightedBooleanProvider)

import orm


class cohortGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["cohort_definition_id"] = generic.numeric.integer_number()
        result["subject_id"] = generic.numeric.integer_number()
        result["cohort_start_date"] = generic.datetime.date()
        result["cohort_end_date"] = generic.datetime.date()
        return result


class cohort_definitionGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["cohort_definition_id"] = generic.numeric.integer_number()
        result["cohort_definition_name"] = generic.person.password(255)
        result["cohort_definition_description"] = generic.text.color()
        result[
            "definition_type_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["cohort_definition_syntax"] = generic.text.color()
        result["subject_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["cohort_initiation_date"] = generic.datetime.date()
        return result


class costGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["cost_event_id"] = generic.numeric.integer_number()
        result["cost_domain_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Domain, "domain_id"
        )
        result["cost_type_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["currency_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["total_charge"] = generic.numeric.float_number()
        result["total_cost"] = generic.numeric.float_number()
        result["total_paid"] = generic.numeric.float_number()
        result["paid_by_payer"] = generic.numeric.float_number()
        result["paid_by_patient"] = generic.numeric.float_number()
        result["paid_patient_copay"] = generic.numeric.float_number()
        result["paid_patient_coinsurance"] = generic.numeric.float_number()
        result["paid_patient_deductible"] = generic.numeric.float_number()
        result["paid_by_primary"] = generic.numeric.float_number()
        result["paid_ingredient_cost"] = generic.numeric.float_number()
        result["paid_dispensing_fee"] = generic.numeric.float_number()
        result["payer_plan_period_id"] = generic.numeric.integer_number()
        result["amount_allowed"] = generic.numeric.float_number()
        result["revenue_code_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["revenue_code_source_value"] = generic.person.password(50)
        result["drg_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["drg_source_value"] = generic.person.password(3)
        return result


class fact_relationshipGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["domain_concept_id_1"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["fact_id_1"] = generic.numeric.integer_number()
        result["domain_concept_id_2"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["fact_id_2"] = generic.numeric.integer_number()
        result["relationship_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        return result


class metadataGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["metadata_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["metadata_type_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["name"] = generic.person.password(250)
        result["value_as_string"] = generic.person.password(250)
        result["value_as_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["value_as_number"] = generic.numeric.float_number()
        result["metadata_date"] = generic.datetime.date()
        result["metadata_datetime"] = generic.datetime.datetime()
        return result


class note_nlpGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["note_id"] = generic.numeric.integer_number()
        result["lexical_variant"] = generic.person.password(250)
        result["nlp_date"] = generic.datetime.date()
        result["section_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["snippet"] = generic.person.password(250)
        result["offset"] = generic.person.password(50)
        result["note_nlp_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result[
            "note_nlp_source_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["nlp_system"] = generic.person.password(250)
        result["nlp_datetime"] = generic.datetime.datetime()
        result["term_exists"] = generic.person.password(1)
        result["term_temporal"] = generic.person.password(50)
        result["term_modifiers"] = generic.person.password(2000)
        return result


class personGenerator(TableGenerator):
    num_rows_per_pass = 5

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["gender_concept_id"] = generic.choice(items=[8507, 8532])
        result["race_concept_id"] = generic.choice(
            items=[8527, 0, 2000001405, 2000001402, 8516, 2000001401]
        )
        result["year_of_birth"] = generic.numeric.integer_number()
        result["ethnicity_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["month_of_birth"] = generic.numeric.integer_number()
        result["day_of_birth"] = generic.numeric.integer_number()
        result["birth_datetime"] = generic.datetime.datetime()
        result["location_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Location, "location_id"
        )
        result["provider_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Provider, "provider_id"
        )
        result["care_site_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.CareSite, "care_site_id"
        )
        result["person_source_value"] = generic.person.password(50)
        result["gender_source_value"] = generic.person.password(50)
        result["gender_source_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["race_source_value"] = generic.person.password(50)
        result["race_source_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["ethnicity_source_value"] = generic.person.password(50)
        result[
            "ethnicity_source_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        return result


class condition_eraGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["condition_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["condition_era_start_date"] = generic.datetime.date()
        result["condition_era_end_date"] = generic.datetime.date()
        result["condition_occurrence_count"] = generic.numeric.integer_number()
        return result


class deathGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["death_date"] = generic.datetime.date()
        result["death_datetime"] = generic.datetime.datetime()
        result["death_type_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["cause_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["cause_source_value"] = generic.person.password(50)
        result["cause_source_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        return result


class dose_eraGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["drug_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["unit_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["dose_value"] = generic.numeric.float_number()
        result["dose_era_start_date"] = generic.datetime.date()
        result["dose_era_end_date"] = generic.datetime.date()
        return result


class drug_eraGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["drug_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["drug_era_start_date"] = generic.datetime.date()
        result["drug_era_end_date"] = generic.datetime.date()
        result["drug_exposure_count"] = generic.numeric.integer_number()
        result["gap_days"] = generic.numeric.integer_number()
        return result


class episodeGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["episode_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["episode_start_date"] = generic.datetime.date()
        result[
            "episode_object_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["episode_type_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["episode_start_datetime"] = generic.datetime.datetime()
        result["episode_end_date"] = generic.datetime.date()
        result["episode_end_datetime"] = generic.datetime.datetime()
        result["episode_parent_id"] = generic.numeric.integer_number()
        result["episode_number"] = generic.numeric.integer_number()
        result["episode_source_value"] = generic.person.password(50)
        result[
            "episode_source_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        return result


class observation_periodGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["observation_period_start_date"] = generic.datetime.date()
        result["observation_period_end_date"] = generic.datetime.date()
        result["period_type_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        return result


class payer_plan_periodGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["payer_plan_period_start_date"] = generic.datetime.date()
        result["payer_plan_period_end_date"] = generic.datetime.date()
        result["payer_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["payer_source_value"] = generic.person.password(50)
        result["payer_source_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["plan_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["plan_source_value"] = generic.person.password(50)
        result["plan_source_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["sponsor_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["sponsor_source_value"] = generic.person.password(50)
        result[
            "sponsor_source_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["family_source_value"] = generic.person.password(50)
        result["stop_reason_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["stop_reason_source_value"] = generic.person.password(50)
        result[
            "stop_reason_source_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        return result


class specimenGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["specimen_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["specimen_type_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["specimen_date"] = generic.datetime.date()
        result["specimen_datetime"] = generic.datetime.datetime()
        result["quantity"] = generic.numeric.float_number()
        result["unit_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["anatomic_site_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result[
            "disease_status_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["specimen_source_id"] = generic.person.password(255)
        result["specimen_source_value"] = generic.person.password(50)
        result["unit_source_value"] = generic.person.password(50)
        result["anatomic_site_source_value"] = generic.person.password(50)
        result["disease_status_source_value"] = generic.person.password(50)
        return result


class visit_occurrenceGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["visit_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["visit_start_date"] = generic.datetime.date()
        result["visit_end_date"] = generic.datetime.date()
        result["visit_type_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["visit_start_datetime"] = generic.datetime.datetime()
        result["visit_end_datetime"] = generic.datetime.datetime()
        result["provider_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Provider, "provider_id"
        )
        result["care_site_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.CareSite, "care_site_id"
        )
        result["visit_source_value"] = generic.person.password(50)
        result["visit_source_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["admitted_from_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["admitted_from_source_value"] = generic.person.password(50)
        result["discharged_to_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["discharged_to_source_value"] = generic.person.password(50)
        result[
            "preceding_visit_occurrence_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitOccurrence, "visit_occurrence_id"
        )
        return result


class episode_eventGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["episode_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Episode, "episode_id"
        )
        result["event_id"] = generic.numeric.integer_number()
        result[
            "episode_event_field_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        return result


class visit_detailGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["visit_detail_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["visit_detail_start_date"] = generic.datetime.date()
        result["visit_detail_end_date"] = generic.datetime.date()
        result[
            "visit_detail_type_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["visit_occurrence_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitOccurrence, "visit_occurrence_id"
        )
        result["visit_detail_start_datetime"] = generic.datetime.datetime()
        result["visit_detail_end_datetime"] = generic.datetime.datetime()
        result["provider_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Provider, "provider_id"
        )
        result["care_site_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.CareSite, "care_site_id"
        )
        result["admitting_source_concept_id"] = generic.numeric.integer_number()
        result["discharge_to_concept_id"] = generic.numeric.integer_number()
        result[
            "preceding_visit_detail_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitDetail, "visit_detail_id"
        )
        result["visit_detail_source_value"] = generic.person.password(120)
        result["visit_detail_source_concept_id"] = generic.person.password(50)
        result["admitting_source_value"] = generic.person.password(50)
        result["discharge_to_source_value"] = generic.person.password(50)
        result["visit_detail_parent_id"] = generic.person.password(50)
        return result


class condition_occurrenceGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["condition_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["condition_start_date"] = generic.datetime.date()
        result[
            "condition_type_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["condition_start_datetime"] = generic.datetime.datetime()
        result["condition_end_date"] = generic.datetime.date()
        result["condition_end_datetime"] = generic.datetime.datetime()
        result["stop_reason"] = generic.person.password(20)
        result["provider_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Provider, "provider_id"
        )
        result["visit_occurrence_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitOccurrence, "visit_occurrence_id"
        )
        result["visit_detail_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitDetail, "visit_detail_id"
        )
        result["condition_source_value"] = generic.person.password(50)
        result[
            "condition_source_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["condition_status_source_value"] = generic.person.password(50)
        result["condition_status_concept_id"] = generic.person.password(50)
        return result


class device_exposureGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["device_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["device_exposure_start_date"] = generic.datetime.date()
        result["device_type_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["device_exposure_start_datetime"] = generic.datetime.datetime()
        result["device_exposure_end_date"] = generic.datetime.date()
        result["device_exposure_end_datetime"] = generic.datetime.datetime()
        result["unique_device_id"] = generic.person.password(255)
        result["quantity"] = generic.numeric.integer_number()
        result["provider_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Provider, "provider_id"
        )
        result["visit_occurrence_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitOccurrence, "visit_occurrence_id"
        )
        result["visit_detail_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitDetail, "visit_detail_id"
        )
        result["device_source_value"] = generic.person.password(50)
        result["device_source_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        return result


class drug_exposureGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["drug_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["drug_exposure_start_date"] = generic.datetime.date()
        result["drug_exposure_end_date"] = generic.datetime.date()
        result["drug_type_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["drug_exposure_start_datetime"] = generic.datetime.datetime()
        result["drug_exposure_end_datetime"] = generic.datetime.datetime()
        result["verbatim_end_date"] = generic.datetime.date()
        result["stop_reason"] = generic.person.password(20)
        result["refills"] = generic.numeric.integer_number()
        result["quantity"] = generic.numeric.float_number()
        result["days_supply"] = generic.numeric.integer_number()
        result["sig"] = generic.text.color()
        result["route_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["lot_number"] = generic.person.password(50)
        result["provider_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Provider, "provider_id"
        )
        result["visit_occurrence_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitOccurrence, "visit_occurrence_id"
        )
        result["visit_detail_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitDetail, "visit_detail_id"
        )
        result["drug_source_value"] = generic.person.password(255)
        result["drug_source_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["route_source_value"] = generic.person.password(50)
        result["dose_unit_source_value"] = generic.person.password(50)
        return result


class measurementGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["measurement_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["measurement_date"] = generic.datetime.date()
        result[
            "measurement_type_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["measurement_datetime"] = generic.datetime.datetime()
        result["measurement_time"] = generic.person.password(10)
        result["operator_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["value_as_number"] = generic.numeric.float_number()
        result["value_as_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["unit_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["range_low"] = generic.numeric.float_number()
        result["range_high"] = generic.numeric.float_number()
        result["provider_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Provider, "provider_id"
        )
        result["visit_occurrence_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitOccurrence, "visit_occurrence_id"
        )
        result["visit_detail_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitDetail, "visit_detail_id"
        )
        result["measurement_source_value"] = generic.person.password(50)
        result[
            "measurement_source_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["unit_source_value"] = generic.person.password(50)
        result["value_source_value"] = generic.person.password(50)
        return result


class noteGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["note_date"] = generic.datetime.date()
        result["note_type_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["note_class_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["note_text"] = generic.text.color()
        result["encoding_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["language_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["note_datetime"] = generic.datetime.datetime()
        result["note_title"] = generic.person.password(250)
        result["provider_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Provider, "provider_id"
        )
        result["visit_occurrence_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitOccurrence, "visit_occurrence_id"
        )
        result["visit_detail_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitDetail, "visit_detail_id"
        )
        result["note_source_value"] = generic.person.password(50)
        result["note_event_id"] = generic.numeric.integer_number()
        result[
            "note_event_field_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        return result


class observationGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["observation_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["observation_date"] = generic.datetime.date()
        result[
            "observation_type_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["observation_datetime"] = generic.datetime.datetime()
        result["value_as_number"] = generic.numeric.float_number()
        result["value_as_string"] = generic.person.password(120)
        result["value_as_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["qualifier_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["unit_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["provider_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Provider, "provider_id"
        )
        result["visit_occurrence_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitOccurrence, "visit_occurrence_id"
        )
        result["visit_detail_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitDetail, "visit_detail_id"
        )
        result["observation_source_value"] = generic.person.password(50)
        result[
            "observation_source_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["unit_source_value"] = generic.person.password(50)
        result["qualifier_source_value"] = generic.person.password(50)
        return result


class procedure_occurrenceGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        pass

    def __call__(self, dst_db_conn):
        result = {}
        result["person_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Person, "person_id"
        )
        result["procedure_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["procedure_date"] = generic.datetime.date()
        result[
            "procedure_type_concept_id"
        ] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["procedure_datetime"] = generic.datetime.datetime()
        result["modifier_concept_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Concept, "concept_id"
        )
        result["quantity"] = generic.numeric.integer_number()
        result["provider_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.Provider, "provider_id"
        )
        result["visit_occurrence_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitOccurrence, "visit_occurrence_id"
        )
        result["visit_detail_id"] = generic.column_value_provider.column_value(
            dst_db_conn, orm.VisitDetail, "visit_detail_id"
        )
        result["procedure_source_value"] = generic.person.password(50)
        result["procedure_source_concept_id"] = generic.numeric.integer_number()
        result["modifier_source_value"] = generic.person.password(50)
        return result


table_generator_dict = {
    "cohort": cohortGenerator(),
    "cohort_definition": cohort_definitionGenerator(),
    "cost": costGenerator(),
    "fact_relationship": fact_relationshipGenerator(),
    "metadata": metadataGenerator(),
    "note_nlp": note_nlpGenerator(),
    "person": personGenerator(),
    "condition_era": condition_eraGenerator(),
    "death": deathGenerator(),
    "dose_era": dose_eraGenerator(),
    "drug_era": drug_eraGenerator(),
    "episode": episodeGenerator(),
    "observation_period": observation_periodGenerator(),
    "payer_plan_period": payer_plan_periodGenerator(),
    "specimen": specimenGenerator(),
    "visit_occurrence": visit_occurrenceGenerator(),
    "episode_event": episode_eventGenerator(),
    "visit_detail": visit_detailGenerator(),
    "condition_occurrence": condition_occurrenceGenerator(),
    "device_exposure": device_exposureGenerator(),
    "drug_exposure": drug_exposureGenerator(),
    "measurement": measurementGenerator(),
    "note": noteGenerator(),
    "observation": observationGenerator(),
    "procedure_occurrence": procedure_occurrenceGenerator(),
}


vocab_dict = {}


story_generator_list = []
