"""This file was auto-generated by sqlsynthgen but can be edited manually."""
from mimesis import Generic
from mimesis.locales import Locale
generic = Generic(locale=Locale.EN)


class advance_decisionGenerator:
    def __init__(self):
        self.advance_decision_type_id = generic.numeric.integer_number()
        self.status_change_datetime = generic.datetime.datetime()


sorted_generators = [advance_decisionGenerator, ]
